### ISSUE TITLE
accepting Invitation from aries-cloudagent-python not working.

### ISSUE THREAD

**Issue by proteche** [hyperledger/aries-framework-javascript#147] opened 2020-12-11 14:13 UTC
when i'm calling `acceptInvitation(connectionId)` function after storing invitation `receiveInvitation(invitationJson, {autoAcceptConnection:false})`to connect with `aries-cloudagent-python` its giving error.

Mediator Logs
```
alice-mediator_1  | 2020-12-11T13:56:22.688Z aries-framework-javascript  error while unpacking message IndyError: 212
alice-mediator_1  |     at Object.callback (/www/node_modules/indy-sdk/src/wrapIndyCallback.js:15:10)
alice-mediator_1  | (node:40) UnhandledPromiseRejectionWarning: IndyError: 212
alice-mediator_1  |     at Object.callback (/www/node_modules/indy-sdk/src/wrapIndyCallback.js:15:10)
alice-mediator_1  | (node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```
Sample Invitation Object from  `aries-cloudagent-python`
```
"invitation": {
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation",
    "@id": "acee0593-e777-4038-aff9-44a5ad5c9d28",
    "label": "Faber.Agent",
    "recipientKeys": [
      "GN55F4ogTgUnoMmg4sZrAGfaW5qG31sQsWY81vfmRuBS"
    ],
    "serviceEndpoint": "https://579f796519b2.ngrok.io"
  },
```

**Comment by TimoGlastra** [comment] 2020-12-14 15:04
Can you see if it works with the PR I opened @proteche?

See #149

**Comment by proteche** [comment] 2020-12-15 07:30
@TimoGlastra it works with web  and not with react-native, the only difference in my code is init agent with  `rn-indy-sdk` for `react-native` & for web i used  `indy-sdk`

**Comment by TimoGlastra** [comment] 2020-12-15 08:53
Interesting. Gonna take a look at React Native

**Comment by proteche** [comment] 2020-12-18 07:10
any updates?

**Comment by TimoGlastra** [comment] 2021-01-13 09:26
@proteche could you verify again? We've made some changes to the framework and it works on our side. We're able to create a connection with ACA-Py with a mediator in between using the mobile agent: https://github.com/animo/aries-mobile-agent-react-native

**Comment by TimoGlastra** [comment] 2021-02-18 12:20
Closing as I'm not able to reproduce

**Closed by TimoGlastra** 2021-02-18 12:20 UTC
Labels: Type: Bug
