### ISSUE TITLE
Node 18.18  indy-vdr not found https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0-dev.16/library

### ISSUE THREAD

**Issue by dnaicker86** [hyperledger/aries-framework-javascript#1579] opened 2023-09-20 07:21 UTC
Created the following [project ](https://github.com/dnaicker86/aries-js-project-1) from tutorials in documentation.

Using node 18.18 via Git Bash Windows 10.

After running `npm install` the following error occurs:

```npm ERR! code 1
npm ERR! path C:\Users\DNaicker\Github\AriesJS\aries-js-project-1\node_modules\@hyperledger\indy-vdr-nodejs
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --target_arch=$(node scripts/arch.js) --target_platform=$(node scripts/platform.js)
npm ERR! response status 404 Not Found on https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@18.18.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\DNaicker\Github\AriesJS\aries-js-project-1\node_modules\@hyperledger\indy-vdr-nodejs\native\indy_vdr.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! stack     at C:\Users\DNaicker\Github\AriesJS\aries-js-project-1\node_modules\@mapbox\node-pre-gyp\lib\install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.18362
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\DNaicker\\Github\\AriesJS\\aries-js-project-1\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--target_arch=$(node" "scripts/arch.js)" "--target_platform=$(node" "scripts/platform.js)"
npm ERR! node-pre-gyp ERR! cwd C:\Users\DNaicker\Github\AriesJS\aries-js-project-1\node_modules\@hyperledger\indy-vdr-nodejs
npm ERR! node-pre-gyp ERR! node -v v18.18.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\DNaicker\AppData\Local\npm-cache\_logs\2023-09-20T07_10_36_767Z-debug-0.log

```

package.json

```
{
  "name": "aries-js-project-1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "run": "ts-node index.ts"
  },
  "dependencies": {
    "@hyperledger/indy-vdr-nodejs": "^0.1.0",
    "@hyperledger/anoncreds-nodejs": "^0.1.0",
    "@hyperledger/aries-askar-nodejs": "^0.1.0",
    "inquirer": "^8.2.5"
  },
  "devDependencies": {
    "@aries-framework/react-native": "*",
    "@hyperledger/aries-askar-react-native": "*",
    "@aries-framework/anoncreds": "*",
    "@aries-framework/anoncreds-rs": "*",
    "@aries-framework/askar": "*",
    "@aries-framework/core": "*",
    "@aries-framework/indy-sdk": "*",
    "@aries-framework/indy-vdr": "*",
    "@aries-framework/cheqd": "*",
    "@aries-framework/node": "*",
    "@types/figlet": "^1.5.4",
    "@types/indy-sdk": "^1.16.26",
    "@types/inquirer": "^8.2.6",
    "clear": "^0.1.0",
    "figlet": "^1.5.2",
    "ts-node": "^10.4.0"
  },
  "overrides": {
    "@cosmjs/amino": "npm:@cosmjs-rn/amino@^0.27.1",
    "@cosmjs/encoding": "npm:@cosmjs-rn/encoding@^0.27.1",
    "@cosmjs/math": "npm:@cosmjs-rn/math@^0.27.1",
    "@cosmjs/stargate": "npm:@cosmjs-rn/stargate@^0.27.1",
    "@cosmjs/tendermint-rpc": "npm:@cosmjs-rn/tendermint-rpc@^0.27.1",
    "@cosmjs/utils": "npm:@cosmjs-rn/utils@^0.27.1",
    "@cosmjs/proto-signing": "npm:@cosmjs-rn/proto-signing@^0.27.1",
    "@cosmjs/crypto": "npm:@cosmjs-rn/crypto@^0.27.1"
  },
  "author": "Denver",
  "license": "ISC"
}

```

**Comment by dnaicker86** [comment] 2023-09-20 07:51
Did the following steps to resolve some of the errors:
1. `npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`
2. Install Python3, fresh installation of Windows was done, so needed to have this in GitBash
3. Am able to compile but not run as the following imports show errors:
```
Cannot find module '@aries-framework/node' or its corresponding type declarations
Cannot find module '@aries-framework/cheqd' or its corresponding type declarations
```
```
import { HttpInboundTransport } from '@aries-framework/node'
import {
  CheqdAnonCredsRegistry,
  CheqdDidRegistrar,
  CheqdDidResolver,
  CheqdModule,
  CheqdModuleConfig,
  CheqdDidCreateOptions,
} from '@aries-framework/cheqd'
```

**Comment by berendsliedrecht** [comment] 2023-09-20 07:53
Will close this as the issue is resolved. Re the modules, you should move them from the `devDependencies` to `dependencies` and likely relaunch your project.

**Closed by berendsliedrecht** 2023-09-20 07:53 UTC

**Comment by dnaicker86** [comment] 2023-09-20 08:03
> Will close this as the issue is resolved. Re the modules, you should move them from the `devDependencies` to `dependencies` and likely relaunch your project.

Have moved them to dependencies but the imports  `'@aries-framework/node` and `@aries-framework/cheqd` cannot be found
