### ISSUE TITLE
AriesFrameworkError: Wallet has not been initialized yet

### ISSUE THREAD

**Issue by Enthusiast-block** [hyperledger/aries-framework-javascript#508] opened 2021-10-30 14:42 UTC
Hi @TimoGlastra , @jakubkoci 

I am following the getting started guide and trying to use AFJ as a module. :- https://github.com/hyperledger/aries-framework-javascript#getting-started

But when I try to create a connection:
https://github.com/hyperledger/aries-framework-javascript/blob/main/docs/getting-started/2-connections.md

This is the error that I am facing :- 
(node:12243) UnhandledPromiseRejectionWarning: AriesFrameworkError: Wallet has not been initialized yet

What is the likely cause of this and how can it be solved?

**Comment by blu3beri** [comment] 2021-10-30 18:06
Hi! 

Did you do step 6 of the agent setup guide?

After creating the agent instance, you should initialize the agent. Like so:

```ts
Await agent.initialize();
```

After this you can use the agent to create connections, issue credentials, etc.

**Comment by Enthusiast-block** [comment] 2021-11-01 17:51
Hi @blu3beri , Thanks

Sorry, My Bad. I wasn't using the await keyword. So it wasn't waiting and it was continuing on its path.
However that issue is resolved.

Now when I try to create the connection and receive the invitation with autoAcceptConnection as True. It is not able to establish the connection. 
I think so it would be because I havnen't set an Inbound Transport on the agent. Can you update the documentation on Transport with InboundTransport support. Also the documentation for credentials and proofs is not updated, I guess.

**Comment by blu3beri** [comment] 2021-11-01 18:21
Ah yes, the document sure needs some more work! We are slowly getting there :). 

Just also make sure both agents have `autoAcceptConnections: true` in their config or when creating and receiving the invitation. It has happened to me before that I only added to one agent. 

I will close this issue now as the problem is resolved, if you have any more questions you can create another issue and we will be happy to help!

**Closed by blu3beri** 2021-11-01 18:21 UTC
